---
# Docker Compose 2.4 is for local development
# https://www.heroku.com/podcasts/codeish/57-discussing-docker-containers-and-kubernetes-with-a-docker-captain - Source on that.
version: '2.4'

x-app: &app
  image: hanami-app:latest
  mem_limit: 512m
  build:
    context: .
    dockerfile: Dockerfile
    target: development
  env_file:
    - .env
  environment:
    REDIS_URL: redis://@redis:6379/1
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/
  volumes:
    - .:/usr/src/app:cached
    - bundler:/usr/local/bundle:delegated
    - node_modules:/usr/src/app/node_modules:delegated
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_started

services:
  postgres:
    image: postgres:12.3-alpine
    mem_limit: 64m
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
      # Alternative if you want to store your postgres data outside of a volume
      #- ~/.docker-data/hanami-app/postgresql:/var/lib/postgresql/data:delegated
    # ports:
    #  - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  redis:
    image: redis:4.0.14-alpine
    mem_limit: 64m
    command: >
      --save
      --maxmemory 128mb
      --maxmemory-policy noeviction
      --stop-writes-on-bgsave-error yes
      --rdbcompression yes
      --rdbchecksum yes
      --dir /data
    volumes:
      - redis:/data:delegated
    # ports:
    #  - 6379
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  web:
    <<: *app
    command: bash -c "rm -rf /usr/src/app/tmp/pids/server.pid && bundle exec hanami server -p 3000 -b '0.0.0.0'"
    ports:
      - "${PORT:-3000}:3000"

volumes:
  postgresql:
  redis:
  bundler:
  node_modules:
